#[allow(dead_code)]
const YAKUS: [(i32, &str, &str); 55] = [
    (0, "menze_tsumo", "門前清自摸和"),
    (1, "riichi", "立直"),
    (2, "ippatsu", "一発"),
    (3, "chankan", "槍槓"),
    (4, "rinsha_kaihou", "嶺上開花"),
    (5, "haite_raoyue", "海底摸月"),
    (6, "houte_raoyui", "河底撈魚"),
    (7, "pinfu", "平和"),
    (8, "tanyao", "断幺九"),
    (9, "iipeiko", "一盃口"),
    (10, "ton", "自風 東"),
    (11, "nan", "自風 南"),
    (12, "xia", "自風 西"),
    (13, "pei", "自風 北"),
    (14, "ton", "場風 東"),
    (15, "nan", "場風 南"),
    (16, "xia", "場風 西"),
    (17, "pei", "場風 北"),
    (18, "haku", "役牌 白"),
    (19, "hatsu", "役牌 發"),
    (20, "chun", "役牌 中"),
    (21, "dabur_riichi", "両立直"),
    (22, "chiitoitsu", "七対子"),
    (23, "chanta", "混全帯幺九"),
    (24, "ittsu", "一気通貫"),
    (25, "sanshok_doujun", "三色同順"),
    (26, "sanshok_doukou", "三色同刻"),
    (27, "sankantsu", "三槓子"),
    (28, "toitoi", "対々和"),
    (29, "sanankou", "三暗刻"),
    (30, "shousangen", "小三元"),
    (31, "honroutou", "混老頭"),
    (32, "ryanpeikou", "二盃口"),
    (33, "junchan", "純全帯幺九"),
    (34, "honitsu", "混一色"),
    (35, "chinitsu", "清一色"),
    (36, "renhou", "人和"),
    (37, "tenhou", "天和"),
    (38, "chihou", "地和"),
    (39, "daisangen", "大三元"),
    (40, "suuankou", "四暗刻"),
    (41, "suuanko_tanki", "四暗刻単騎"),
    (42, "tsuuiisou", "字一色"),
    (43, "ryuuiisou", "緑一色"),
    (44, "chinroutou", "清老頭"),
    (45, "chuure_pouto", "九蓮宝燈"),
    (46, "chuure_pout_9_wait", "純正九蓮宝燈"),
    (47, "kokush_musou", "国士無双"),
    (48, "kokush_muso_13_wait", "国士無双１３面"),
    (49, "daisuushi", "大四喜"),
    (50, "shousuushi", "小四喜"),
    (51, "suukantsu", "四槓子"),
    (52, "dora", "ドラ"),
    (53, "uradora", "裏ドラ"),
    (54, "akadora", "赤ドラ")];