name: Create Release

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Tag name'
        required: true
      release_name:
        description: 'Release name'
        required: true
      release_body:
        description: 'Release body'
        required: false

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Build for x86_64-unknown-linux-gnu
        run: cargo build --release --target x86_64-unknown-linux-gnu

      - name: Build for x86_64-pc-windows-msvc
        run: cargo build --release --target x86_64-pc-windows-msvc

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.event.inputs.tag_name }}
          release_name: ${{ github.event.inputs.release_name }}
          body: ${{ github.event.inputs.release_body }}
          draft: false
          prerelease: false

      - name: Upload Linux artifact
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: target/x86_64-unknown-linux-gnu/release/your_project_name
          asset_name: your_project_name-linux
          asset_content_type: application/octet-stream

      - name: Upload Windows artifact
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: target/x86_64-pc-windows-msvc/release/your_project_name.exe
          asset_name: your_project_name-windows.exe
          asset_content_type: application/octet-stream
